config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root to: 'home#index'

  get 'home/index'

  resources :property do
    get 'download', on: :member
    get 'destroy_reporting', on: :member
  end

  resources :lost

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'hoge' && password == 'hogehoge'
  end
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lost.rb
class Lost < ApplicationRecord
  has_one :property

  validates :current_location, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :token, uniqueness: true, presence: true
  validates :is_lost, inclusion: { in: [true, false] }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :properties
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    user = current_user
    properties = Property.where(user_id: user.id)
    @losts = properties.select{|p| p.is_lost == true }
    @possesions = properties - @losts
  end
end

app/controllers/lost_controller.rb
class LostController < ApplicationController
  def index
  end
  
  def new
    @lost = Lost.new
    @token = params['token']
  end

  def create
    @lost = Lost.new
    token = params['token']
    
    property = Property.where(token: token).first

    if !(property.present?)
      flash[:danger] = "このQRコードは無効です" 
      redirect_to lost_index_path
    else
      property_name = property.name

      user_email = User.find(property.user_id).email
      
      # TODO: エラーハンドリング
      @lost.current_location = params['lost']['current_location']
      @lost.pickup_location = params['lost']['pickup_location']
      @lost.property_id = property.id
      @lost.save

      property.is_lost = true
      property.lost_id = @lost.id
      current_loc = @lost.current_location
      pickup_loc = @lost.pickup_location
      property.save

      ReportingMailer.report_email(
        user_email,
        property_name,
        current_loc,
        pickup_loc
      ).deliver!
      #ReportingWorker.perform_async(user_email, property_name, current_loc, pickup_loc)
      
      redirect_to lost_index_path
    end
  end
end

app/controllers/property_controller.rb
class PropertyController < ApplicationController
  before_action :authenticate_user! 
  
  def show
    @property = Property.find(params['id'])

    check_user(@property.user)
    
    if @property.is_lost
      @lost = Lost.find(@property.lost_id)
    end
  end

  def download
    property = Property.find(params['id'])

    check_user(property.user)

    qrcode = CreateQRCode::get_image(request, property.token)
    send_data(qrcode, type: 'image/png')
  end
  
  def new
    @property = Property.new
  end

  def create
    @property = Property.new

    @property.name = params['property']['name']
    @property.user_id = current_user.id
    @property.token = SecureRandom.hex(30)    # とりあえず30にしとけば被らんだろ
    @property.is_lost = false

    if @property.save
      flash[:success] = '物品を正しく登録しました'
      redirect_to home_index_path
    else
      flash[:danger] = '物品名を入力していることを確認してください。'
      render 'new'
    end
  end

  def edit
    @property = Property.find(params['id'])

    check_user(@property.user)
  end

  def update
    property = Property.find(params['id'])

    check_user(property.user)
    
    property.name = params['property']['name']
    property.user_id = current_user.id

    if property.save
      flash[:success] = '物品を正しく登録しました'
      redirect_to home_index_path
    else
      flash[:danger] = '物品名を入力していることを確認してください。'
      render 'new'
    end
  end

  def destroy
    property = Property.find(params['id'])

    check_user(property.user)
    
    if property.destroy
      flash[:success] = '物品を削除しました'
      redirect_to home_index_path
    else
      flash[:danger] = '物品を削除できません。管理者にお問い合わせください'
      redirect_to home_index_path
    end
  end

  def destroy_reporting
    property = Property.find(params['id'])
    lost = Lost.find(property.lost_id)

    property.lost_id = nil
    property.is_lost = false
    property.token = SecureRandom.hex(30)    # 一回拾得報告されたらQRコードを更新
    
    if lost.destroy && property.save
      flash[:success] = '物品の受取を登録しました'
      redirect_to home_index_path
    else
      flash[:danger] = '登録を削除できません。管理者にお問い合わせください'
      redirect_to home_index_path
    end
  end

  private

  def check_user(user)
    if user != current_user
      flash[:danger] = '権限の無い操作です'
      redirect_to home_index_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lost_helper.rb
module LostHelper
end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Dashboard</h1>
  <hr>
  <%= link_to '新規に物品を登録する', new_property_path, class: 'btn btn-primary btn-block'%>
  <hr>
  <% if !@losts.empty? %>
  <span style="color:red"><h2>紛失が報告されている物品</h2></span>
    <table class="table">
      <tr>
        <td>物品名</td>
      </tr>
      <% @losts.each do |l| %>
      <tr>
        <td><%= link_to l.name, property_path(l.id) %></td>
      </tr>
      <% end %>
    </table>
  <hr>
  <% end %>
  <h2>紛失報告のない物品</h2>
  <table class="table">
    <tr>
      <td>物品名</td>
      <td>削除</td>
    </tr>
    <% @possesions.each do |p| %>
    <tr>
      <td>
        <%= link_to p.name, property_path(p.id) %>
      </td>
      <td>
        <%= link_to '削除', property_path(p.id), method: 'delete', class: 'btn btn-danger btn-xs'%>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lostify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Lostify', root_path, class: 'navbar-brand'%>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if user_signed_in? %>
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="contaier">
      <div class="col-xs-12 col-md-12">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if flash[:success] %>
          <p class="alert alert-success"><%= flash[:success] %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <% if flash[:danger] %>
          <p class="alert alert-danger"><%= flash[:danger] %></p>
        <% end %>
      </div>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/lost/index.html.erb
<div class="container">
  <div align="center">
  <h2>ご協力ありがとうございました</h2>
  <h3><u>所持人にいち早く返還いたします</u></h3>
  <hr>
  <h2>Lostify</h2>
  </div>
</div>

app/views/lost/new.html.erb
<div class="container">
  <h2 align="center">拾得物の返還にご協力いただき</h2>
  <h2 align="center">ありがとうございます</h2>
  <hr>
  <h3 align="center">持ち主に返還するため</h3>
  <h3 align="center">以下のフォームにご回答ください</h3>
  <hr>
  <div class="col-xs-0  col-sm-2"></div>
  <div class="col-xs-12 col-sm-8">
    <%= form_for @lost, url: {action: 'create'}, class: 'form-group' do |f| %>
    <div class="form-group">
      <%= f.label 'この拾得物は、どこで拾われましたか？' %>
      <%= f.text_field :pickup_location, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.label '拾得後、どこにお届けいただきましたか？' %>
      <%= f.text_field :current_location, class: 'form-control'%>
    </div>
    <%= f.hidden_field_tag :token, @token %>
    <div class="form-group">
      <%= f.submit '確定', class: 'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>

app/views/property/edit.html.erb
<div class="container">
  <h2>物品情報の変更</h2>
  <hr>
  <div class="col-xs-0  col-sm-2"></div>
  <div class="col-xs-12 col-sm-8">
    <%= form_for @property, url: {action: 'update'}, class: 'form-group' do |f| %>
    <div class="form-group">
      <%= f.label '物品名' %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.submit '登録', class: 'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>

app/views/property/new.html.erb
<div class="container">
  <h2>物品の新規登録</h2>
  <hr>
  <div class="col-xs-0  col-sm-2"></div>
  <div class="col-xs-12 col-sm-8">
    <%= form_for @property, url: {action: 'create'}, class: 'form-group' do |f| %>
    <div class="form-group">
      <%= f.label '物品名' %>
      <%= f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= f.submit '登録', class: 'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>

app/views/property/show.html.erb
<div class="container">
  <h2><%= @property.name %></h2>
  <hr>
  <%= link_to '物品名を変更する', edit_property_path(@property.id), class: 'btn btn-primary btn-block'%>
  <hr>
  <% if @property.is_lost %>
  <h3 align="center">
    <span style="color:red">紛失報告があります</span>
  </h3>
    <table class="table">
      <tr>
        <td><b>現在届けられている場所<b></td>
        <td><%= @lost.current_location %></td>
      </tr>
      <tr>
        <td><b>拾得された場所</b></td>
        <td><%= @lost.pickup_location %></td>
      </tr>
    </table>
  <% else %>
    紛失報告はありません
  <% end %>
  <hr>
  <% if @property.is_lost %>
    <%= link_to '紛失物の受取登録', destroy_reporting_property_path(@property.id), class: 'btn btn-warning btn-block'%>
  <% else %>
    <%= link_to 'QRコードをダウンロード', download_property_path(@property.id), class: 'btn btn-success btn-block'%>
  <% end %>
</div>